### ISSUE TITLE
the cesium tutorial does not work

### ISSUE THREAD

**Issue by elfia** [aardgoose/CVTiles#1]
Hi, 
I can't open the cesium tutorial - https://aardgoose.github.io/CVTiles/cesiumtiles.html it returns 404 error.
I am new to therion and haven't used cesium nor 3d tiles, if there is a tutorial or documentation how to use this it would be quite helpful
Thanks,
Efi

**Comment by aardgoose** [comment]
I have added the missing file (I had forgotten to write it!).  It is quite simple to use the Cesium tiles and avoids a lot of work, hope this helps.

**Comment by elfia** [comment]
Hi, thanks, the tutorial is now there but for some reason it is not working for me. I am not sure if I should post it in another issue or here. When I add the settings:
```
displayCRS: "ORIGINAL",
cesiumAccessToken: "here is my token copied from the cesium website",
defaultCRS: "+proj=utm +zone=34 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
```
The menu with buttons- terrain, survey, information etc. is not showing. I have only changed the token and the zone (East Europe, Bulgaria). Also there is an error in the console:
```
Error: WebGL warning: <SetDimensions>: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.
```
(the error is visible only in Firefox) 
In Chrome I do not see the error but on both browsers it tries to download "undefined" image when the `displayCRS: "ORIGINAL"` option is set.
```
GET https://pod-rb.eu/karta-na-kolkina/3d/undefined 404
``` 
If I remove `displayCRS: "ORIGINAL",` then the menu is displayed but there is no 3d terrain something like orange layer but 2d. Should I include also some script from Cesium - similar to Bing and OSM providers? 

I am using version 1.15 of CaveView
This is the cave project - [https://pod-rb.eu/karta-na-kolkina/3d/](https://pod-rb.eu/karta-na-kolkina/3d/ )

Thanks,
Efi

**Comment by elfia** [comment]
Hi, is the tutorial working with CaveView 1.15?

**Comment by aardgoose** [comment]
Hi,  apologies for delay.

I am releasing v2 now, you can see a working  setup using the Cesium tiles at:
https://aardgoose.github.io/CaveView.js/demo2.html now.  

The documentation changes will follow shortly, and I'll take a look at your issue.

**Comment by elfia** [comment]
Ok, I will wait for the new version and instructions. I am closing this issue, thanks for support!
